Updated POM & Release pipeline (#10)
* Updated POM to include gitflow maven plugin config

* Updated Release Pipeline

---------

Co-authored-by: OmOmofonmwan <omomofonmwan@tinkarbuild.com>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -7,14 +7,14 @@ on:
   workflow_dispatch:
     inputs:
       modules:
-       type: choice
-       description: Module
-       required: true
-       options:
-        - --SELECT--
-        - data-properties
-        - tinkar-starter-data-properties
-        - tinkar-example-data-properties
+        type: choice
+        description: Module
+        required: true
+        options:
+          - --SELECT--
+          - data-properties
+          - tinkar-starter-data-properties
+          - tinkar-example-data-properties
       release_version:
         type: string
         description: "(Optional) Custom Release Version"
@@ -41,14 +41,14 @@ jobs:
     if: github.repository_owner == 'ikmdev'
     defaults:
       run:
-       working-directory: ${{env.MODULE}}
+        working-directory: ${{env.MODULE}}
     steps:
       - name: Verify Module Selection
         if: inputs.modules == '-- SELECT --'
         run: |
           echo "ERROR: Please pick a correct module from the selection"
           exit 1
-          
+
       - name: Verify Branch
         if: env.BRANCH_NAME != env.TRUNK_BRANCH_NAME
         run: |
@@ -60,9 +60,51 @@ jobs:
         with:
           token: ${{secrets.IKMDEVOPS_PAT_TOKEN}}
 
-      - name: Shared Release Action
-        uses: ikmdev/maven-semver-release-action@v2
+      - name: Setup Java
+        uses: actions/setup-java@v4
         with:
-          version_type: ${{ github.event.inputs.version_type }}
-          github_token: ${{secrets.GITHUB_TOKEN}}
-          release_version: ${{ github.event.inputs.release_version }}
+          distribution: 'zulu'
+          java-version: 21
+
+      - name: Configure Version Type
+        id: configure_version_type
+        shell: bash
+        run: |
+          if [ $RELEASE_TYPE == 'major' ]; then 
+           echo "version_type=0" >> $GITHUB_OUTPUT
+          elif [ $RELEASE_TYPE == 'minor' ]; then
+           echo "version_type=1" >> $GITHUB_OUTPUT
+          elif [ $RELEASE_TYPE == 'patch' ]; then
+           echo "version_type=2" >> $GITHUB_OUTPUT
+          elif [ $RELEASE_TYPE == 'pre-release' ]; then
+           echo "version_type=3" >> $GITHUB_OUTPUT
+          else
+           echo "ERROR: Invalid version_type '${{ inputs.version_type }}'."
+           exit 1
+          fi
+        env:
+          RELEASE_TYPE: ${{inputs.version_type}}
+
+      - name: Setup Git User
+        run: |
+          git config user.name "ikmdevops"
+          git config user.email "devops@ikm.dev"
+
+      - name: GitFlow Release
+        id: gitflow_release
+        run: |
+          mvn gitflow:release \
+             --batch-mode \
+             -X \
+             -Dverbose=true \
+             -DallowSnapshots=true \
+             -DreleaseVersion=${{ inputs.release_version }} \
+             -DversionDigitToIncrement=${{ steps.configure_version_type.outputs.version_type }} \
+             -DdevelopmentVersion=${{ inputs.development_version }} \
+             -DpostReleaseGoals="clean install \
+                   --batch-mode \
+                   -e \
+                   -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
+                   -PcodeQuality,release-enforcement \
+                   -PgenerateData \
+                   -Dmaven.build.cache.enabled=false"
